"""
Indian Crop Disease Knowledge Base
-----------------------------------
Comprehensive disease data for 7 major Indian crops with Indian-market
chemical treatments, organic solutions, dosage per acre, and prevention.
"""

DISEASE_DATABASE = {
    # ═══════════════════════════════════════════════════════════════════
    #   RICE
    # ═══════════════════════════════════════════════════════════════════
    "Rice___Blast": {
        "disease_name": "Rice Blast",
        "crop": "Rice",
        "symptoms": [
            "Diamond-shaped lesions on leaves with grey centers",
            "Brown borders around leaf spots",
            "Neck rot causing panicle breakage",
            "White to grey lesions on nodes",
        ],
        "cause": "Fungus Magnaporthe oryzae, spread by wind-borne spores in humid conditions (25–28°C)",
        "description": "Rice blast is one of the most devastating diseases of rice in India, capable of destroying an entire crop in severe cases. The fungus attacks leaves, nodes, and panicles, reducing grain filling and causing significant yield loss up to 70–80% in susceptible varieties.",
        "severity": "High",
        "spread_risk": "High",
        "organic_treatment": [
            "Apply neem oil spray (5 ml/litre of water) at 10-day intervals",
            "Use Trichoderma viride bio-fungicide (4 g/litre) as seed treatment and foliar spray",
            "Spray Pseudomonas fluorescens (10 g/litre) at tillering and panicle initiation stages",
            "Maintain proper spacing to allow air circulation",
        ],
        "chemical_treatment": [
            "Tricyclazole 75% WP (Baan/Beam) — 0.6 g/litre foliar spray",
            "Isoprothiolane 40% EC (Fujione) — 1.5 ml/litre",
            "Carbendazim 50% WP (Bavistin) — 1 g/litre as preventive spray",
            "Kasugamycin 3% SL (Kasu-B) — 2 ml/litre at first symptom appearance",
        ],
        "dosage": "Tricyclazole: 300 g/acre in 200 litres of water. Spray at boot-leaf and heading stage. Repeat after 15 days if needed.",
        "prevention": [
            "Use blast-resistant varieties (Pusa Basmati 1509, IR64)",
            "Avoid excess nitrogen fertilisation",
            "Maintain field sanitation — remove crop residues",
            "Ensure proper water management — avoid drought stress",
            "Treat seeds with Carbendazim (2 g/kg seed) before sowing",
        ],
    },
    "Rice___Brown_Spot": {
        "disease_name": "Rice Brown Spot",
        "crop": "Rice",
        "symptoms": [
            "Oval brown spots on leaves with grey centres",
            "Dark brown spots on leaf sheaths and glumes",
            "Poor grain filling with discoloured grains",
            "Seedling blight in nursery beds",
        ],
        "cause": "Fungus Bipolaris oryzae (Cochliobolus miyabeanus), favoured by nutrient-deficient soils and temperatures of 25–30°C",
        "description": "Rice brown spot is associated with mineral-deficient soils, particularly low silicon and potassium. It was the primary cause of the Great Bengal Famine of 1943. The disease causes significant yield reduction through poor grain filling and seed discolouration.",
        "severity": "Medium",
        "spread_risk": "Medium",
        "organic_treatment": [
            "Apply Pseudomonas fluorescens (10 g/litre) as foliar spray",
            "Use Trichoderma harzianum (4 g/kg) as seed treatment",
            "Spray neem kernel extract (5%) at 15-day intervals",
            "Apply Panchagavya (3%) foliar spray for plant immunity",
        ],
        "chemical_treatment": [
            "Mancozeb 75% WP (Dithane M-45) — 2.5 g/litre",
            "Carbendazim 50% WP (Bavistin) — 1 g/litre",
            "Propiconazole 25% EC (Tilt) — 1 ml/litre",
            "Zineb 75% WP (Indofil Z-78) — 2 g/litre",
        ],
        "dosage": "Mancozeb: 500 g/acre in 200 litres of water. Apply at tillering stage and repeat after 15 days.",
        "prevention": [
            "Apply balanced fertilisation (NPK + micronutrients)",
            "Use certified disease-free seed",
            "Apply silicon-based fertilisers to strengthen plant cells",
            "Avoid prolonged flooding — maintain alternate wetting and drying",
            "Seed treatment with Carbendazim (2 g/kg seed)",
        ],
    },
    "Rice___Leaf_Blight": {
        "disease_name": "Rice Bacterial Leaf Blight",
        "crop": "Rice",
        "symptoms": [
            "Water-soaked lesions starting from leaf tips and margins",
            "Yellowish-white streaks along leaf veins",
            "Leaves dry up and turn greyish-white",
            "Bacterial ooze visible on leaves in early morning",
        ],
        "cause": "Bacterium Xanthomonas oryzae pv. oryzae, spread through rain splash and contaminated irrigation water",
        "description": "Bacterial leaf blight is one of the most serious rice diseases in South and Southeast Asia. It can cause yield losses of 20–50% in severe epidemics. The disease is particularly destructive during the kharif season in flooded paddies.",
        "severity": "High",
        "spread_risk": "High",
        "organic_treatment": [
            "Spray Pseudomonas fluorescens (10 g/litre) at 10-day intervals",
            "Apply neem oil (5 ml/litre) mixed with copper-based organic formulation",
            "Use Bacillus subtilis-based bio-pesticide (5 g/litre)",
            "Foliar spray of turmeric extract (5%) as a natural bactericide",
        ],
        "chemical_treatment": [
            "Streptomycin sulphate + Tetracycline (Streptocycline) — 0.5 g + Copper oxychloride 2.5 g/litre",
            "Copper hydroxide 77% WP (Kocide) — 2 g/litre",
            "Copper oxychloride 50% WP (Blitox) — 2.5 g/litre",
        ],
        "dosage": "Streptocycline 6 g + Copper oxychloride 500 g per acre in 200 litres of water. Spray at first symptom and repeat after 10 days.",
        "prevention": [
            "Use resistant varieties (Improved Samba Mahsuri, Swarna)",
            "Avoid excess nitrogen — use balanced NPK",
            "Drain excess standing water from fields",
            "Avoid clipping leaves during transplanting",
            "Disinfect tools and avoid working in wet fields",
        ],
    },
    "Rice___Healthy": {
        "disease_name": "Healthy",
        "crop": "Rice",
        "symptoms": [],
        "cause": "No disease detected",
        "description": "Your rice plant looks healthy! The leaves show normal green coloration with no signs of infection, spots, or lesions. Continue with your current crop management practices to maintain plant health.",
        "severity": "None",
        "spread_risk": "None",
        "organic_treatment": [
            "Continue regular neem oil spray (3 ml/litre) as a preventive measure",
            "Apply Panchagavya (3%) foliar spray once a month for plant vitality",
            "Maintain mulching with organic matter to improve soil health",
        ],
        "chemical_treatment": [
            "No chemical treatment needed",
            "Optional preventive spray of Mancozeb (1.5 g/litre) before monsoon season",
        ],
        "dosage": "No treatment dosage needed. For preventive Mancozeb: 300 g/acre in 200 litres of water.",
        "prevention": [
            "Maintain balanced NPK fertilisation",
            "Ensure proper water management — alternate wetting and drying",
            "Monitor fields regularly for early signs of pest or disease",
            "Rotate crops with pulses to maintain soil health",
        ],
    },

    # ═══════════════════════════════════════════════════════════════════
    #   WHEAT
    # ═══════════════════════════════════════════════════════════════════
    "Wheat___Leaf_Rust": {
        "disease_name": "Wheat Leaf Rust",
        "crop": "Wheat",
        "symptoms": [
            "Small, round, orange-brown pustules on upper leaf surface",
            "Pustules scattered randomly on leaves",
            "Premature leaf drying in severe cases",
            "Reduced ear head size and grain shrivelling",
        ],
        "cause": "Fungus Puccinia triticina, spread by wind-borne uredospores over long distances",
        "description": "Leaf rust (brown rust) is the most common wheat rust in India, appearing annually in the Indo-Gangetic plains. It reduces photosynthetic area leading to 15–30% yield loss. The disease is favour by temperatures of 15–22°C with high humidity.",
        "severity": "Medium",
        "spread_risk": "High",
        "organic_treatment": [
            "Spray neem oil (5 ml/litre) at early pustule stage",
            "Apply Trichoderma viride (4 g/litre) as preventive foliar spray",
            "Use buttermilk spray (10%) as a natural fungicide — traditional remedy",
            "Remove and destroy heavily infected leaves",
        ],
        "chemical_treatment": [
            "Propiconazole 25% EC (Tilt) — 1 ml/litre",
            "Tebuconazole 25.9% EC (Folicur) — 1 ml/litre",
            "Mancozeb 75% WP (Dithane M-45) — 2.5 g/litre",
            "Triadimefon 25% WP (Bayleton) — 1 g/litre",
        ],
        "dosage": "Propiconazole: 200 ml/acre in 200 litres of water. Spray at flag-leaf stage when first pustules appear. One spray usually sufficient.",
        "prevention": [
            "Grow rust-resistant varieties (HD 3086, DBW 187, PBW 725)",
            "Timely sowing — avoid late planting",
            "Monitor fields from January onwards in North India",
            "Avoid excessive nitrogen — promotes lush growth susceptible to rust",
        ],
    },
    "Wheat___Powdery_Mildew": {
        "disease_name": "Wheat Powdery Mildew",
        "crop": "Wheat",
        "symptoms": [
            "White powdery patches on upper leaf surface",
            "Patches later turn grey-brown with black fruiting bodies",
            "Stunted growth and reduced tillering",
            "Premature leaf senescence",
        ],
        "cause": "Fungus Blumeria graminis f. sp. tritici, spread by wind and favoured by cool humid weather (15–22°C)",
        "description": "Powdery mildew can cause 15–20% yield reduction in wheat. It is common in irrigated wheat in northern India, especially in areas with dense canopy and high humidity. The fungus directly reduces photosynthesis and grain size.",
        "severity": "Medium",
        "spread_risk": "Medium",
        "organic_treatment": [
            "Spray milk solution (1:10 dilution with water) on affected leaves",
            "Apply potassium bicarbonate (3 g/litre) as foliar spray",
            "Use sulphur-based organic formulation (3 g/litre)",
            "Neem oil spray (5 ml/litre) at 10-day intervals",
        ],
        "chemical_treatment": [
            "Karathane 48% EC (Dinocap) — 1 ml/litre",
            "Propiconazole 25% EC (Tilt) — 1 ml/litre",
            "Sulfex (Wettable Sulphur) 80% WP — 3 g/litre",
            "Triadimefon 25% WP (Bayleton) — 1 g/litre",
        ],
        "dosage": "Sulfex: 600 g/acre in 200 litres of water. Apply at first sign of powdery growth. Repeat after 15 days if disease persists.",
        "prevention": [
            "Avoid excess irrigation — allow topsoil to dry between waterings",
            "Ensure proper plant spacing for air circulation",
            "Grow resistant varieties where available",
            "Avoid heavy nitrogen doses in late season",
        ],
    },
    "Wheat___Healthy": {
        "disease_name": "Healthy",
        "crop": "Wheat",
        "symptoms": [],
        "cause": "No disease detected",
        "description": "Your wheat plant appears healthy with no visible signs of disease. The leaves show normal green colour and there are no lesions, spots, or fungal growth observed.",
        "severity": "None",
        "spread_risk": "None",
        "organic_treatment": [
            "Apply preventive neem oil spray (3 ml/litre) every 2 weeks",
            "Use vermicompost top-dressing for improved soil biology",
        ],
        "chemical_treatment": [
            "No treatment needed",
        ],
        "dosage": "No treatment dosage required.",
        "prevention": [
            "Continue balanced fertilisation",
            "Monitor fields regularly during tillering and heading stages",
            "Maintain proper irrigation scheduling",
        ],
    },

    # ═══════════════════════════════════════════════════════════════════
    #   TOMATO
    # ═══════════════════════════════════════════════════════════════════
    "Tomato___Late_Blight": {
        "disease_name": "Tomato Late Blight",
        "crop": "Tomato",
        "symptoms": [
            "Large, dark brown water-soaked patches on leaves",
            "White fungal growth on underside of leaves in humid conditions",
            "Dark brown lesions on stems",
            "Firm dark spots on green and ripe fruits",
        ],
        "cause": "Oomycete Phytophthora infestans, favoured by cool wet weather (15–20°C with high humidity)",
        "description": "Late blight is the most destructive disease of tomato in India, especially during the rabi season and in hilly regions. It can destroy an entire crop within 7–10 days under favorable conditions. The pathogen also attacks potatoes, making management critical.",
        "severity": "High",
        "spread_risk": "High",
        "organic_treatment": [
            "Spray Bordeaux mixture (1%) — 10 g copper sulphate + 10 g lime per litre of water",
            "Apply Trichoderma viride (4 g/litre) as preventive spray before monsoon",
            "Use Pseudomonas fluorescens (10 g/litre) foliar spray",
            "Remove and destroy infected plant parts immediately",
        ],
        "chemical_treatment": [
            "Metalaxyl 8% + Mancozeb 64% WP (Ridomil Gold) — 2.5 g/litre",
            "Cymoxanil 8% + Mancozeb 64% WP (Curzate M8) — 3 g/litre",
            "Copper oxychloride 50% WP (Blitox) — 2.5 g/litre",
            "Dimethomorph 50% WP (Acrobat) — 1 g/litre",
        ],
        "dosage": "Ridomil Gold: 500 g/acre in 200 litres of water. Spray at first symptom and repeat every 7–10 days during wet weather. Alternate with contact fungicides.",
        "prevention": [
            "Use disease-free transplants from certified nurseries",
            "Provide staking and proper spacing for air circulation",
            "Avoid overhead irrigation — use drip irrigation",
            "Apply mulch to prevent soil splash",
            "Destroy volunteer plants and crop residues after harvest",
        ],
    },
    "Tomato___Early_Blight": {
        "disease_name": "Tomato Early Blight",
        "crop": "Tomato",
        "symptoms": [
            "Dark brown concentric ring spots (target board pattern) on lower leaves",
            "Yellowing around leaf spots",
            "Leaf drop starting from bottom of plant",
            "Dark sunken spots near fruit stem end",
        ],
        "cause": "Fungus Alternaria solani, favoured by warm humid conditions (24–29°C) and stressed plants",
        "description": "Early blight is common across India wherever tomatoes are grown. It starts on older, lower leaves and progresses upward. Yield losses of 20–40% are common. Stressed plants (drought, nutrient deficiency) are more susceptible.",
        "severity": "Medium",
        "spread_risk": "Medium",
        "organic_treatment": [
            "Spray Trichoderma viride (4 g/litre) starting from transplanting",
            "Apply neem oil (5 ml/litre) every 10 days",
            "Use baking soda spray (5 g/litre) as a foliar treatment",
            "Apply compost tea drench to build soil microbe diversity",
        ],
        "chemical_treatment": [
            "Mancozeb 75% WP (Dithane M-45) — 2.5 g/litre",
            "Chlorothalonil 75% WP (Kavach) — 2 g/litre",
            "Azoxystrobin 23% SC (Amistar) — 1 ml/litre",
            "Carbendazim 12% + Mancozeb 63% WP (SAAF) — 2 g/litre",
        ],
        "dosage": "Mancozeb: 500 g/acre in 200 litres of water. Start at first symptom and spray every 10–14 days. Rotate fungicide groups to prevent resistance.",
        "prevention": [
            "Use resistant/tolerant varieties (Arka Rakshak, Arka Abhed)",
            "Maintain adequate nutrition — don't stress plants with hunger",
            "Use drip irrigation to avoid wetting foliage",
            "Stake plants and prune lower branches for air flow",
            "Rotate with non-solanaceous crops for 2–3 seasons",
        ],
    },
    "Tomato___Leaf_Curl": {
        "disease_name": "Tomato Leaf Curl Virus",
        "crop": "Tomato",
        "symptoms": [
            "Upward curling and cupping of leaves",
            "Thickened, leathery leaf texture",
            "Stunted plant growth with short internodes",
            "Yellow margins on curled leaves",
            "Flowers drop without fruit set",
        ],
        "cause": "Tomato Leaf Curl Virus (ToLCV), transmitted by whitefly (Bemisia tabaci)",
        "description": "Leaf curl virus is the most economically important tomato disease in India, especially in summer season. Yield losses can reach 80–100% when infection occurs at an early stage. The disease is transmitted by the silverleaf whitefly, which is prevalent across India.",
        "severity": "High",
        "spread_risk": "High",
        "organic_treatment": [
            "Install yellow sticky traps (12 per acre) to monitor and trap whiteflies",
            "Spray neem oil (5 ml/litre) every 7 days to repel whiteflies",
            "Apply Verticillium lecanii (5 g/litre) — a whitefly bio-control agent",
            "Intercrop with marigold to repel whiteflies",
            "Uproot and destroy infected plants immediately",
        ],
        "chemical_treatment": [
            "Imidacloprid 17.8% SL (Confidor) — 0.3 ml/litre for whitefly control",
            "Thiamethoxam 25% WG (Actara) — 0.3 g/litre",
            "Diafenthiuron 50% WP (Polo) — 1 g/litre",
            "Spiromesifen 22.9% SC (Oberon) — 0.5 ml/litre for nymphal stages",
        ],
        "dosage": "Imidacloprid: 60 ml/acre in 200 litres of water. Spray at seedling stage and repeat every 15 days. Alternate insecticide groups to prevent resistance in whiteflies.",
        "prevention": [
            "Use ToLCV-resistant hybrids (Arka Ananya, TH-1, Lakshmi)",
            "Raise nursery under insect-proof nylon net (40–50 mesh)",
            "Transplant during cooler months when whitefly is less active",
            "Remove weeds around fields — whitefly harbours on alternate hosts",
            "Avoid planting near cotton fields (cotton is a whitefly host)",
        ],
    },
    "Tomato___Septoria_Leaf_Spot": {
        "disease_name": "Tomato Septoria Leaf Spot",
        "crop": "Tomato",
        "symptoms": [
            "Small circular spots (2–3 mm) with dark brown borders and grey centres",
            "Tiny black dots (pycnidia) visible in spot centres",
            "Starts on lower leaves and moves upward",
            "Severe defoliation in advanced stages",
        ],
        "cause": "Fungus Septoria lycopersici, spread by rain splash and overhead irrigation",
        "description": "Septoria leaf spot causes significant early defoliation of tomato plants. While it rarely infects fruit directly, the loss of foliage results in sunscalded fruit and reduced yields of 30–50%. It is common during humid, rainy seasons.",
        "severity": "Medium",
        "spread_risk": "Medium",
        "organic_treatment": [
            "Remove and destroy infected lower leaves",
            "Apply Trichoderma viride (4 g/litre) as preventive spray",
            "Spray copper-based organic fungicide (Bordeaux mixture 1%)",
            "Improve air circulation with proper staking and pruning",
        ],
        "chemical_treatment": [
            "Mancozeb 75% WP (Dithane M-45) — 2.5 g/litre",
            "Chlorothalonil 75% WP (Kavach) — 2 g/litre",
            "Hexaconazole 5% SC (Contaf) — 1 ml/litre",
            "Azoxystrobin 23% SC (Amistar) — 1 ml/litre",
        ],
        "dosage": "Mancozeb: 500 g/acre in 200 litres. Spray at first symptom, repeat every 10 days. Alternate with systemic fungicide every third application.",
        "prevention": [
            "Avoid overhead irrigation — use drip",
            "Mulch around plants to prevent soil splash",
            "Remove lower leaves that touch the ground",
            "Rotate with non-solanaceous crops for 2 years",
        ],
    },
    "Tomato___Healthy": {
        "disease_name": "Healthy",
        "crop": "Tomato",
        "symptoms": [],
        "cause": "No disease detected",
        "description": "Your tomato plant looks healthy! The leaves are green with no spots, curling, or unusual markings. Keep up your current management practices.",
        "severity": "None",
        "spread_risk": "None",
        "organic_treatment": ["Continue preventive neem oil spray (3 ml/litre) every 2 weeks"],
        "chemical_treatment": ["No treatment needed"],
        "dosage": "No dosage required.",
        "prevention": [
            "Monitor for whiteflies using yellow sticky traps",
            "Maintain proper staking and air circulation",
            "Use balanced NPK fertilisation",
        ],
    },

    # ═══════════════════════════════════════════════════════════════════
    #   POTATO
    # ═══════════════════════════════════════════════════════════════════
    "Potato___Late_Blight": {
        "disease_name": "Potato Late Blight",
        "crop": "Potato",
        "symptoms": [
            "Dark brown water-soaked patches on leaf margins and tips",
            "White cottony fungal growth on underside of leaves",
            "Rapid browning and collapse of foliage",
            "Brown rotting of tubers from surface inwards",
        ],
        "cause": "Oomycete Phytophthora infestans, favoured by cool wet conditions (12–18°C with high humidity)",
        "description": "Late blight is historically the single most destructive potato disease worldwide. In India, it is severe in the hills (Shimla, Darjeeling) and plains (UP, West Bengal) during foggy winter periods. It can cause 40–80% crop loss within 2 weeks.",
        "severity": "High",
        "spread_risk": "High",
        "organic_treatment": [
            "Spray Bordeaux mixture (1%) as preventive before rains",
            "Apply Trichoderma viride (4 g/litre) foliar spray",
            "Use Pseudomonas fluorescens (10 g/litre) bio-fungicide",
            "Hill up soil around stems to protect tubers from spore infection",
        ],
        "chemical_treatment": [
            "Metalaxyl 8% + Mancozeb 64% WP (Ridomil Gold) — 2.5 g/litre",
            "Cymoxanil 8% + Mancozeb 64% WP (Curzate M8) — 3 g/litre",
            "Mancozeb 75% WP (Dithane M-45) — 2.5 g/litre (preventive only)",
            "Fenamidone 10% + Mancozeb 50% WG (Sectin) — 3 g/litre",
        ],
        "dosage": "Ridomil Gold: 500 g/acre in 200 litres. Spray at first symptom, repeat every 7 days during wet weather. Alternate systemic and contact fungicides.",
        "prevention": [
            "Use certified disease-free seed tubers",
            "Plant resistant varieties (Kufri Girdhari, Kufri Khyati)",
            "Avoid overhead sprinkler irrigation",
            "Destroy volunteer plants and cull piles",
            "Apply prophylactic fungicide spray before forecasted foggy/rainy weather",
        ],
    },
    "Potato___Early_Blight": {
        "disease_name": "Potato Early Blight",
        "crop": "Potato",
        "symptoms": [
            "Dark brown concentric ring spots on older leaves (target board pattern)",
            "Yellowing around spots",
            "Premature senescence of lower leaves",
            "Small dark sunken lesions on tuber surface",
        ],
        "cause": "Fungus Alternaria solani, favoured by warm days (25–30°C) and cool nights with dew",
        "description": "Early blight is a chronic disease of potato in India, occurring every season. It reduces photosynthetic area leading to 20–30% yield loss. Nutritionally stressed and older plants are most susceptible.",
        "severity": "Medium",
        "spread_risk": "Medium",
        "organic_treatment": [
            "Spray neem oil (5 ml/litre) every 10 days",
            "Apply Trichoderma viride (4 g/litre) foliar application",
            "Remove and destroy heavily infected lower leaves",
            "Maintain soil health with compost and humic acid application",
        ],
        "chemical_treatment": [
            "Mancozeb 75% WP (Dithane M-45) — 2.5 g/litre",
            "Carbendazim 12% + Mancozeb 63% WP (SAAF) — 2 g/litre",
            "Azoxystrobin 23% SC (Amistar) — 1 ml/litre",
            "Chlorothalonil 75% WP (Kavach) — 2 g/litre",
        ],
        "dosage": "Mancozeb: 500 g/acre in 200 litres. Start at 45 days after planting and repeat every 10–14 days.",
        "prevention": [
            "Use healthy seed tubers from certified sources",
            "Maintain proper nutrition — don't let plants become hungry",
            "Irrigation management — avoid alternate drought and flood",
            "Crop rotation with cereals for 2+ seasons",
        ],
    },
    "Potato___Healthy": {
        "disease_name": "Healthy",
        "crop": "Potato",
        "symptoms": [],
        "cause": "No disease detected",
        "description": "Your potato plant looks healthy with normal green foliage and no signs of blight, spots, or viral infection.",
        "severity": "None",
        "spread_risk": "None",
        "organic_treatment": ["Continue preventive care with neem oil spray every 2 weeks"],
        "chemical_treatment": ["No treatment needed"],
        "dosage": "No dosage required.",
        "prevention": [
            "Monitor for late blight during foggy/dew periods",
            "Maintain balanced fertilisation",
            "Earth up tubers properly to prevent greening",
        ],
    },

    # ═══════════════════════════════════════════════════════════════════
    #   COTTON
    # ═══════════════════════════════════════════════════════════════════
    "Cotton___Bacterial_Blight": {
        "disease_name": "Cotton Bacterial Blight",
        "crop": "Cotton",
        "symptoms": [
            "Small angular water-soaked spots on leaves (angular leaf spot)",
            "Spots enlarge, turn brown, and may coalesce",
            "Black arm symptoms on stems and branches",
            "Boll rot with brown-black discolouration",
        ],
        "cause": "Bacterium Xanthomonas citri pv. malvacearum, spread by rain splash and contaminated seed",
        "description": "Bacterial blight (angular leaf spot) is one of the oldest known diseases of cotton in India. It is most damaging in Central and South India during monsoon season with warm, humid weather. Severe infections can cause 30–40% yield loss.",
        "severity": "High",
        "spread_risk": "High",
        "organic_treatment": [
            "Spray Pseudomonas fluorescens (10 g/litre) at 10-day intervals",
            "Apply copper-based organic spray (Bordeaux mixture 1%)",
            "Use neem oil (5 ml/litre) with turmeric extract (2%) as foliar spray",
            "Remove and burn infected plant debris after harvest",
        ],
        "chemical_treatment": [
            "Streptomycin sulphate (Streptocycline) — 0.5 g/litre + Copper oxychloride 2.5 g/litre",
            "Copper hydroxide 77% WP (Kocide) — 2 g/litre",
            "Copper oxychloride 50% WP (Blitox) — 2.5 g/litre",
        ],
        "dosage": "Streptocycline 6 g + Copper oxychloride 500 g per acre in 200 litres. Start at first symptom and repeat after 10 days.",
        "prevention": [
            "Use acid-delinted disease-free seed",
            "Seed treatment with Carboxin (2 g/kg) or Streptocycline (1 g/10 litres water for seed soak)",
            "Grow resistant varieties (Suraj, NH 615)",
            "Avoid working in fields when plants are wet",
            "Crop rotation with cereals for 2+ years",
        ],
    },
    "Cotton___Leaf_Curl": {
        "disease_name": "Cotton Leaf Curl Virus",
        "crop": "Cotton",
        "symptoms": [
            "Upward curling of leaf margins",
            "Thickening and darkening of leaf veins (vein swelling)",
            "Cup-shaped leaves with enation (outgrowths) on underside",
            "Stunted plant growth with reduced boll formation",
        ],
        "cause": "Cotton Leaf Curl Virus (CLCuV), transmitted by whitefly (Bemisia tabaci)",
        "description": "Cotton leaf curl disease is one of the most devastating cotton diseases in northwestern India (Punjab, Haryana, Rajasthan). It caused massive epidemics in the 1990s. Yield losses can reach 50–80% in susceptible varieties.",
        "severity": "High",
        "spread_risk": "High",
        "organic_treatment": [
            "Install yellow sticky traps (15 per acre) for whitefly management",
            "Spray neem oil (5 ml/litre) every 7 days",
            "Apply Verticillium lecanii (5 g/litre) against whitefly nymphs",
            "Uproot and destroy infected plants early to prevent virus spread",
        ],
        "chemical_treatment": [
            "Imidacloprid 17.8% SL (Confidor) — 0.3 ml/litre",
            "Thiamethoxam 25% WG (Actara) — 0.3 g/litre",
            "Diafenthiuron 50% WP (Polo) — 1 g/litre",
            "Pyriproxyfen 10% EC (Lano) — 1 ml/litre (targets whitefly eggs and nymphs)",
        ],
        "dosage": "Imidacloprid: 60 ml/acre in 200 litres. Start from 15 days after germination, repeat every 15 days. Rotate insecticide groups.",
        "prevention": [
            "Grow CLCuV-tolerant Bt cotton hybrids",
            "Avoid early sowing — plant after first June rains to escape peak whitefly",
            "Avoid planting near old cotton crop residues",
            "Keep borders clean — remove weeds that harbour whiteflies",
        ],
    },
    "Cotton___Healthy": {
        "disease_name": "Healthy",
        "crop": "Cotton",
        "symptoms": [],
        "cause": "No disease detected",
        "description": "Your cotton plant looks healthy with normal leaf growth and no signs of curling, spots, or bacterial infection.",
        "severity": "None",
        "spread_risk": "None",
        "organic_treatment": ["Continue preventive neem oil spray"],
        "chemical_treatment": ["No treatment needed"],
        "dosage": "No dosage required.",
        "prevention": ["Monitor for whiteflies weekly", "Maintain balanced fertilisation"],
    },

    # ═══════════════════════════════════════════════════════════════════
    #   MAIZE
    # ═══════════════════════════════════════════════════════════════════
    "Maize___Northern_Leaf_Blight": {
        "disease_name": "Maize Northern Leaf Blight",
        "crop": "Maize",
        "symptoms": [
            "Long elliptical greyish-green lesions (5–15 cm) on leaves",
            "Lesions start on lower leaves and progress upwards",
            "Severe blight can kill entire leaves",
            "Reduced ear size and grain filling",
        ],
        "cause": "Fungus Exserohilum turcicum, favoured by moderate temperatures (18–27°C) with high humidity and dew",
        "description": "Northern leaf blight (turcicum blight) is the most important foliar disease of maize in India. It is common in the hilly regions and during the kharif season in the plains. Yield losses of 30–50% can occur when the upper leaves are severely infected before tasseling.",
        "severity": "High",
        "spread_risk": "Medium",
        "organic_treatment": [
            "Apply Trichoderma viride (4 g/litre) as foliar spray at 10-day intervals",
            "Spray neem oil (5 ml/litre) at first symptom",
            "Remove heavily infected lower leaves to slow spread",
            "Use Pseudomonas fluorescens (10 g/litre)",
        ],
        "chemical_treatment": [
            "Mancozeb 75% WP (Dithane M-45) — 2.5 g/litre",
            "Propiconazole 25% EC (Tilt) — 1 ml/litre",
            "Azoxystrobin 23% SC (Amistar) — 1 ml/litre",
            "Zineb 75% WP (Indofil Z-78) — 2 g/litre",
        ],
        "dosage": "Mancozeb: 500 g/acre in 200 litres. First spray at knee-high stage, repeat at pre-tassel. Apply Propiconazole if severe.",
        "prevention": [
            "Use resistant hybrids (HQPM-1, DHM 117)",
            "Remove and destroy crop residues after harvest",
            "Avoid mono-cropping of maize — rotate with pulses or oilseeds",
            "Maintain balanced NPK with adequate potassium for disease resistance",
        ],
    },
    "Maize___Common_Rust": {
        "disease_name": "Maize Common Rust",
        "crop": "Maize",
        "symptoms": [
            "Small circular to elongated brownish-red pustules on both leaf surfaces",
            "Pustules burst to release powdery brown spores",
            "In severe cases, leaves turn brown and dry up",
        ],
        "cause": "Fungus Puccinia sorghi, spread by wind-borne spores",
        "description": "Common rust is widespread across all maize-growing regions of India. It is usually moderate in severity but can cause 15–25% yield loss when infection occurs early.",
        "severity": "Medium",
        "spread_risk": "High",
        "organic_treatment": [
            "Apply neem oil (5 ml/litre) at early pustule stage",
            "Spray Trichoderma viride (4 g/litre) preventively",
        ],
        "chemical_treatment": [
            "Mancozeb 75% WP (Dithane M-45) — 2.5 g/litre",
            "Propiconazole 25% EC (Tilt) — 1 ml/litre",
            "Hexaconazole 5% SC (Contaf) — 2 ml/litre",
        ],
        "dosage": "Propiconazole: 200 ml/acre in 200 litres. One spray usually sufficient at flag-leaf stage.",
        "prevention": [
            "Grow resistant hybrids",
            "Timely sowing to avoid peak infection period",
            "Remove volunteer maize plants",
        ],
    },
    "Maize___Healthy": {
        "disease_name": "Healthy",
        "crop": "Maize",
        "symptoms": [],
        "cause": "No disease detected",
        "description": "Your maize plant is healthy with vigorous green leaves and no disease symptoms.",
        "severity": "None",
        "spread_risk": "None",
        "organic_treatment": ["Continue good agronomic practices"],
        "chemical_treatment": ["No treatment needed"],
        "dosage": "No dosage required.",
        "prevention": ["Monitor for fall armyworm and leaf blight during kharif season"],
    },

    # ═══════════════════════════════════════════════════════════════════
    #   SUGARCANE
    # ═══════════════════════════════════════════════════════════════════
    "Sugarcane___Red_Rot": {
        "disease_name": "Sugarcane Red Rot",
        "crop": "Sugarcane",
        "symptoms": [
            "Drying and withering of the 3rd and 4th leaves from top",
            "Internal cane tissue turns red with white patches (brick-red and white cross-section)",
            "Sour alcoholic smell from split cane",
            "Shrinkage and hollowing of internodes",
        ],
        "cause": "Fungus Colletotrichum falcatum, spread through infected setts (seed cane) and soil",
        "description": "Red rot is called the 'cancer of sugarcane' and is the most devastating disease in Indian sugarcane cultivation. It has historically wiped out entire varieties in India (e.g. Co 997). The disease is soil-borne and seed-borne, making management challenging.",
        "severity": "High",
        "spread_risk": "High",
        "organic_treatment": [
            "Treat setts with Trichoderma viride (10 g/litre) for 30 minutes before planting",
            "Apply Pseudomonas fluorescens as soil drench around root zone",
            "Use Bacillus subtilis-based bio-agent at planting",
            "Practice hot water treatment of setts at 52°C for 30 minutes (traditional method)",
        ],
        "chemical_treatment": [
            "Carbendazim 50% WP (Bavistin) — sett treatment (1 g/litre for 30 min dip)",
            "Thiophanate Methyl 70% WP (Topsin-M) — 1 g/litre sett dip",
            "No effective foliar treatment once disease is established",
        ],
        "dosage": "Carbendazim: Prepare 1 g/litre solution. Dip setts for 30 minutes before planting. 200 litres solution per acre of setts.",
        "prevention": [
            "Use red rot-resistant varieties (Co 0238, CoLk 94184)",
            "Always use disease-free seed cane from declared disease-free nurseries",
            "Avoid ratooning of susceptible varieties",
            "Remove and destroy infected stools — do not leave in field",
            "Flood fields for 7 days to kill soil-borne inoculum before planting",
        ],
    },
    "Sugarcane___Smut": {
        "disease_name": "Sugarcane Smut",
        "crop": "Sugarcane",
        "symptoms": [
            "Long black whip-like structure (5–100 cm) emerging from growing point",
            "Whip is initially covered with silvery membrane that ruptures to release black spores",
            "Thin, grass-like tillers with narrow leaves",
            "Excessive tillering from infected stool",
        ],
        "cause": "Fungus Sporisorium scitamineum, spread by wind-borne spores and infected setts",
        "description": "Whip smut is easily recognizable by the black whip emerging from the top of the plant. It is common across India and can cause 30–40% yield loss. Ratooning increases disease severity significantly.",
        "severity": "Medium",
        "spread_risk": "Medium",
        "organic_treatment": [
            "Hot water treatment of setts at 52°C for 30 minutes",
            "Apply Trichoderma viride (10 g/litre) sett treatment",
            "Remove and burn smutted whips before they release spores",
        ],
        "chemical_treatment": [
            "Carbendazim 50% WP (Bavistin) — 1 g/litre sett dip for 30 minutes",
            "Triadimefon 25% WP (Bayleton) — 1 g/litre foliar spray on ratoon cane",
        ],
        "dosage": "Carbendazim: 1 g/litre sett dip for 30 min before planting.",
        "prevention": [
            "Use smut-resistant varieties (CoLk 94184, Co 0238)",
            "Avoid ratooning for more than 2 cycles",
            "Rogue out smutted clumps before whips open",
            "Use only healthy setts from disease-free nurseries",
        ],
    },
    "Sugarcane___Healthy": {
        "disease_name": "Healthy",
        "crop": "Sugarcane",
        "symptoms": [],
        "cause": "No disease detected",
        "description": "Your sugarcane looks healthy with strong cane growth and no visible symptoms of rot, smut, or leaf scald.",
        "severity": "None",
        "spread_risk": "None",
        "organic_treatment": ["Maintain good agronomic practices"],
        "chemical_treatment": ["No treatment needed"],
        "dosage": "No dosage required.",
        "prevention": ["Always use disease-free setts from certified nurseries"],
    },

    # ═══════════════════════════════════════════════════════════════════
    #   ADDITIONAL COTTON PESTS & DISEASES
    # ═══════════════════════════════════════════════════════════════════
    "Cotton___American_Bollworm": {
        "disease_name": "American Bollworm",
        "crop": "Cotton",
        "symptoms": [
            "Circular bore holes on bolls with frass (excreta) visible",
            "Larvae feeding inside bolls, damaging lint and seeds",
            "Shedding of squares and young bolls",
            "Damaged bolls show rotting due to secondary fungal infection",
        ],
        "cause": "Helicoverpa armigera larvae — polyphagous pest active during flowering and boll formation stages",
        "description": "American bollworm (Helicoverpa armigera) is the most destructive pest of cotton in India. A single larva can damage 30–40 bolls during its life cycle. It bore into bolls and feeds on developing seeds and lint, causing 30–60% yield loss.",
        "severity": "High",
        "spread_risk": "High",
        "organic_treatment": [
            "Install pheromone traps (Helilure) at 5 traps/acre to monitor and mass-trap male moths",
            "Release Trichogramma chilonis egg parasitoid (1 lakh eggs/acre) at 15-day intervals from squaring",
            "Spray HaNPV (Helicoverpa Nuclear Polyhedrosis Virus) at 250 LE/acre in evening hours",
            "Apply neem seed kernel extract (NSKE 5%) at 10-day intervals during flowering",
            "Hand-pick and destroy large larvae in early mornings",
        ],
        "chemical_treatment": [
            "Emamectin Benzoate 5% SG (Proclaim) — 4 g/10 litres",
            "Chlorantraniliprole 18.5% SC (Coragen) — 3 ml/10 litres",
            "Spinosad 45% SC (Tracer) — 3 ml/10 litres",
            "Indoxacarb 14.5% SC (Avaunt) — 10 ml/10 litres",
        ],
        "dosage": "Emamectin Benzoate: 80 g/acre in 200 litres water. Spray at ETL of 1 larva/plant at evening hours. Rotate chemistry to prevent resistance.",
        "prevention": [
            "Grow trap crops (pigeon pea, marigold) on borders to divert moth egg-laying",
            "Use Bt cotton hybrids with bollworm resistance genes",
            "Install bird perches (20/acre) to encourage predatory birds",
            "Deep plough after harvest to expose pupae to sunlight and predators",
            "Avoid mono-cropping of cotton year after year",
        ],
    },
    "Cotton___Anthracnose": {
        "disease_name": "Cotton Anthracnose",
        "crop": "Cotton",
        "symptoms": [
            "Small reddish-brown spots on leaves and stems",
            "Sunken, dark lesions on bolls with pink spore masses in humid weather",
            "Seedling blight with damping off in nursery",
            "Boll rot leading to lint discolouration",
        ],
        "cause": "Fungus Colletotrichum gossypii, seed-borne and spread by rain splash",
        "description": "Cotton anthracnose affects seedlings, leaves, and bolls. It is most destructive as a boll rot during wet seasons, causing lint staining and reducing market grade. Yield losses of 10–25% are common in susceptible varieties during monsoon.",
        "severity": "Medium",
        "spread_risk": "Medium",
        "organic_treatment": [
            "Seed treatment with Trichoderma viride (4 g/kg seed) before sowing",
            "Spray Pseudomonas fluorescens (10 g/litre) at 15-day intervals",
            "Apply neem oil (5 ml/litre) at first symptom appearance",
            "Remove and destroy infected plant debris",
        ],
        "chemical_treatment": [
            "Carbendazim 50% WP (Bavistin) — 1 g/litre",
            "Mancozeb 75% WP (Dithane M-45) — 2.5 g/litre",
            "Copper oxychloride 50% WP (Blitox) — 2.5 g/litre",
        ],
        "dosage": "Carbendazim: 200 g/acre in 200 litres water. Spray at first symptom, repeat after 15 days.",
        "prevention": [
            "Use acid-delinted, disease-free certified seed",
            "Seed treatment with Carboxin (2 g/kg seed)",
            "Avoid dense planting — maintain proper spacing",
            "Crop rotation with cereals for 2+ years",
        ],
    },
    "Cotton___Aphid": {
        "disease_name": "Cotton Aphid",
        "crop": "Cotton",
        "symptoms": [
            "Curling and distortion of young leaves",
            "Sticky honeydew deposits on leaf surfaces",
            "Black sooty mould developing on honeydew",
            "Yellowing and stunted plant growth",
        ],
        "cause": "Aphis gossypii — sap-sucking pest that multiplies rapidly in warm humid conditions",
        "description": "Cotton aphid is a major sucking pest across all cotton-growing regions of India. Large colonies on the undersides of leaves drain plant sap, leading to reduced vigour. Honeydew deposits attract sooty mould and reduce lint quality.",
        "severity": "Medium",
        "spread_risk": "High",
        "organic_treatment": [
            "Spray neem oil (5 ml/litre) at 7-day intervals",
            "Release ladybird beetles (Coccinella septempunctata) — natural predator of aphids",
            "Apply Verticillium lecanii (5 g/litre) bio-insecticide",
            "Use yellow sticky traps (12/acre) for monitoring",
        ],
        "chemical_treatment": [
            "Imidacloprid 17.8% SL (Confidor) — 0.3 ml/litre",
            "Thiamethoxam 25% WG (Actara) — 0.3 g/litre",
            "Flonicamid 50% WG (Ulala) — 0.3 g/litre",
            "Dimethoate 30% EC (Rogor) — 1.7 ml/litre",
        ],
        "dosage": "Imidacloprid: 60 ml/acre in 200 litres water. Spray when aphid population crosses ETL of 10 per leaf. Rotate with different mode of action.",
        "prevention": [
            "Avoid excess nitrogen fertilisation which promotes succulent growth",
            "Maintain field sanitation — remove alternate weed hosts",
            "Conserve natural enemies by avoiding broad-spectrum insecticides",
            "Seed treatment with Imidacloprid (5 g/kg seed) for early protection",
        ],
    },
    "Cotton___Boll_Rot": {
        "disease_name": "Cotton Boll Rot",
        "crop": "Cotton",
        "symptoms": [
            "Bolls show soft, water-soaked discolouration",
            "Opening of bolls reveals rotted lint with foul smell",
            "Black or brown fungal growth on boll surface",
            "Premature boll dropping",
        ],
        "cause": "Complex of fungi (Aspergillus, Fusarium, Rhizopus) — often secondary infection after bollworm damage or prolonged wetness",
        "description": "Boll rot complex is a group of fungal infections that collectively damage cotton bolls, especially during prolonged wet weather. It is often secondary to bollworm or pink bollworm damage and can cause 15–30% boll loss.",
        "severity": "Medium",
        "spread_risk": "Medium",
        "organic_treatment": [
            "Apply Trichoderma viride (4 g/litre) as preventive foliar spray",
            "Spray Pseudomonas fluorescens (10 g/litre) at boll formation stage",
            "Remove and destroy infected bolls promptly",
            "Maintain proper drainage to reduce humidity around bolls",
        ],
        "chemical_treatment": [
            "Carbendazim 50% WP (Bavistin) — 1 g/litre",
            "Copper oxychloride 50% WP (Blitox) — 2.5 g/litre",
            "Mancozeb 75% WP (Dithane M-45) — 2.5 g/litre",
        ],
        "dosage": "Carbendazim: 200 g/acre in 200 litres. Spray at first sign of boll rot, repeat after 10 days.",
        "prevention": [
            "Control bollworms effectively — boll damage is the primary entry point",
            "Avoid dense canopy — maintain proper spacing and plant architecture",
            "Ensure good drainage in the field",
            "Avoid late irrigation during boll maturation",
        ],
    },
    "Cotton___Bollworm": {
        "disease_name": "Cotton Bollworm",
        "crop": "Cotton",
        "symptoms": [
            "Bore holes on squares, flowers, and bolls",
            "Frass visible at entry holes",
            "Damaged bolls with partially eaten seeds and lint",
            "Premature shedding of squares and small bolls",
        ],
        "cause": "Earias vittella and Earias insulana (spotted and spiny bollworm) — larvae bore into fruiting parts",
        "description": "Spotted and spiny bollworms are major pests of cotton in India, active from squaring to boll maturation. Unlike American bollworm, these are smaller but bore into tender shoots, squares, and bolls, causing 20–40% damage.",
        "severity": "High",
        "spread_risk": "Medium",
        "organic_treatment": [
            "Install pheromone traps for monitoring adult moth activity",
            "Release Trichogramma chilonis (1 lakh eggs/acre) at fortnightly intervals",
            "Spray NSKE 5% at 10-day intervals",
            "Apply Bacillus thuringiensis (Bt) spray (2 g/litre) at early larval stage",
        ],
        "chemical_treatment": [
            "Emamectin Benzoate 5% SG (Proclaim) — 4 g/10 litres",
            "Chlorantraniliprole 18.5% SC (Coragen) — 3 ml/10 litres",
            "Profenophos 50% EC (Curacron) — 2 ml/litre",
        ],
        "dosage": "Emamectin Benzoate: 80 g/acre in 200 litres. Spray at ETL of 10% damaged fruiting parts.",
        "prevention": [
            "Collect and destroy fallen squares and damaged bolls weekly",
            "Remove shoot tips harbouring larvae",
            "Deep ploughing after harvest to expose pupae",
            "Use resistant/tolerant Bt cotton hybrids",
        ],
    },
    "Cotton___Mealy_Bug": {
        "disease_name": "Cotton Mealy Bug",
        "crop": "Cotton",
        "symptoms": [
            "White cotton-like waxy masses on stems, leaves, and bolls",
            "Bushy appearance — stunted terminal growth due to shortened internodes",
            "Sooty mould on honeydew deposits",
            "Distorted and crinkled leaves",
        ],
        "cause": "Phenacoccus solenopsis — invasive sap-sucking pest that secretes white waxy covering",
        "description": "Cotton mealy bug became a major invasive pest in India since 2006. Colonies settle in leaf axils, on stems, and on bolls, sucking sap and injecting toxins. Severe infestations cause 30–60% yield loss and reduce lint quality.",
        "severity": "High",
        "spread_risk": "High",
        "organic_treatment": [
            "Release parasitoid Aenasius bambawalei (100 per acre) — highly effective bio-control",
            "Spray neem oil (5 ml/litre) to disrupt waxy coating",
            "Apply Verticillium lecanii (5 g/litre) at 10-day intervals",
            "Use pressurised water jet to dislodge colonies from plants",
        ],
        "chemical_treatment": [
            "Profenophos 50% EC (Curacron) — 2 ml/litre",
            "Buprofezin 25% SC (Applaud) — 2 ml/litre (targets nymphs)",
            "Thiamethoxam 25% WG (Actara) — 0.5 g/litre",
        ],
        "dosage": "Profenophos: 400 ml/acre in 200 litres. Spray with high-volume nozzle to penetrate waxy covering. Two sprays at 10-day intervals.",
        "prevention": [
            "Destroy previous crop residues — burn or deep plough",
            "Maintain weed-free borders — Parthenium is major alternate host",
            "Monitor fields from July onwards for early detection",
            "Conserve natural enemies — avoid broad-spectrum early-season sprays",
        ],
    },
    "Cotton___Whitefly": {
        "disease_name": "Cotton Whitefly",
        "crop": "Cotton",
        "symptoms": [
            "Tiny white flying insects under leaves when disturbed",
            "Sticky honeydew on leaves and bolls",
            "Black sooty mould on honeydew reducing photosynthesis",
            "Yellowing and downward curling of leaves in severe infestations",
        ],
        "cause": "Bemisia tabaci — sap-sucking pest that also transmits leaf curl virus",
        "description": "Cotton whitefly is both a direct pest (sap sucking) and vector of Cotton Leaf Curl Virus. Severe outbreaks in Punjab and Haryana (2015) caused massive crop losses. Honeydew contamination makes lint sticky and unmarketable.",
        "severity": "High",
        "spread_risk": "High",
        "organic_treatment": [
            "Install yellow sticky traps (15/acre) for monitoring and mass trapping",
            "Spray neem oil (5 ml/litre) every 7 days",
            "Release Encarsia formosa or Chrysoperla carnea (bio-control agents)",
            "Apply Verticillium lecanii (5 g/litre) against nymphs",
        ],
        "chemical_treatment": [
            "Diafenthiuron 50% WP (Polo) — 1 g/litre",
            "Spiromesifen 22.9% SC (Oberon) — 0.5 ml/litre",
            "Pyriproxyfen 10% EC (Lano) — 1 ml/litre",
            "Thiamethoxam 25% WG (Actara) — 0.3 g/litre",
        ],
        "dosage": "Diafenthiuron: 200 g/acre in 200 litres. Rotate mode of action every spray. Spray undersides of leaves.",
        "prevention": [
            "Remove alternate weed hosts around fields",
            "Avoid early sowing — delays overlap with peak whitefly season",
            "Use resistant varieties where available",
            "Seed treatment with Imidacloprid (5 g/kg) for early-season protection",
        ],
    },
    "Cotton___Pink_Bollworm": {
        "disease_name": "Pink Bollworm",
        "crop": "Cotton",
        "symptoms": [
            "Rosette flowers — petals stuck together unable to open normally",
            "Green bolls show entry holes with pink larvae inside",
            "Double seeds (fused seed pairs) in cross-section of boll",
            "Premature boll opening with damaged lint",
        ],
        "cause": "Pectinophora gossypiella larvae — bore into green bolls and feed on developing seeds",
        "description": "Pink bollworm is one of the most damaging pests of cotton in India, especially in Central India (Maharashtra, Gujarat, Madhya Pradesh). Larvae feed inside green bolls causing 20–50% yield loss. It is the primary pest that has developed resistance to Bt cotton.",
        "severity": "High",
        "spread_risk": "High",
        "organic_treatment": [
            "Install pheromone traps (Gossyplure) at 5/acre for monitoring",
            "Release Trichogramma achaeae (1 lakh/acre) at boll initiation",
            "Spray NSKE 5% at green boll stage",
            "Practice mass trapping with 40 pheromone traps/acre",
        ],
        "chemical_treatment": [
            "Chlorantraniliprole 18.5% SC (Coragen) — 3 ml/10 litres",
            "Quinalphos 25% EC (Ekalux) — 2 ml/litre",
            "Cypermethrin 25% EC — 1 ml/litre (use only if needed)",
        ],
        "dosage": "Chlorantraniliprole: 60 ml/acre in 200 litres. Spray at first sign of rosette flowers. Repeat after 15 days.",
        "prevention": [
            "Destroy crop residues immediately after last picking",
            "Do not carry-over kapas (seed cotton) in fields — pink bollworm pupae survive",
            "Plant early-maturing varieties to escape late-season build-up",
            "Maintain crop-free period (June–July) before new season",
        ],
    },
    "Cotton___Red_Bug": {
        "disease_name": "Red Cotton Bug",
        "crop": "Cotton",
        "symptoms": [
            "Bright red and black bugs clustered on open bolls",
            "Staining of lint with yellowish-brown spots from bug excreta",
            "Seeds appear shrivelled due to sap extraction",
            "Reduced oil content in cottonseed",
        ],
        "cause": "Dysdercus koenigii (red cotton bug) — sap-sucking pest that feeds on mature bolls",
        "description": "Red cotton bug is a stainer pest — it stains the lint with its excreta, reducing market grade and price. It is active during boll opening and feeds on ripening seeds, reducing seed viability and oil content. Commonly seen in Central and South India.",
        "severity": "Medium",
        "spread_risk": "Medium",
        "organic_treatment": [
            "Hand-collect bugs in early morning when they are sluggish",
            "Spray neem oil (5 ml/litre) on open bolls",
            "Remove alternate host weeds (Sida, Abutilon) near fields",
            "Use light traps at night to monitor and trap adults",
        ],
        "chemical_treatment": [
            "Malathion 50% EC — 2 ml/litre",
            "Lambda Cyhalothrin 5% EC (Karate) — 1 ml/litre",
            "Dimethoate 30% EC (Rogor) — 1.7 ml/litre",
        ],
        "dosage": "Malathion: 400 ml/acre in 200 litres. Spray on open bolls in evening. One spray usually sufficient.",
        "prevention": [
            "Timely picking of open bolls — don't let kapas remain in field",
            "Remove and destroy alternate weed hosts (Sida spp.) from field borders",
            "Clean ginning areas — bugs harbour in stored seed cotton",
        ],
    },
    "Cotton___Thrips": {
        "disease_name": "Cotton Thrips",
        "crop": "Cotton",
        "symptoms": [
            "Upward curling of leaf margins (leaf curl due to thrips, not virus)",
            "Silvery-white streaks on leaf surface",
            "Brownish-yellow discolouration of leaves",
            "Seedlings show crinkling and stunted growth",
        ],
        "cause": "Thrips tabaci — tiny rasping-sucking insects that lacerate leaf cells",
        "description": "Cotton thrips is a major early-season pest in India, attacking seedlings and young plants. The tiny insects rasp leaf surfaces and suck cell sap, causing upward leaf curling and silvery patches. Severe seedling-stage attack can delay crop establishment.",
        "severity": "Medium",
        "spread_risk": "Medium",
        "organic_treatment": [
            "Spray neem oil (5 ml/litre) at 7-day intervals on seedlings",
            "Apply Verticillium lecanii (5 g/litre) on nymphs",
            "Use blue sticky traps (8/acre) for monitoring",
            "Intercrop with onion or garlic — natural thrips repellents",
        ],
        "chemical_treatment": [
            "Fipronil 5% SC (Regent) — 2 ml/litre",
            "Imidacloprid 17.8% SL (Confidor) — 0.3 ml/litre",
            "Spinosad 45% SC (Tracer) — 3 ml/10 litres",
        ],
        "dosage": "Fipronil: 400 ml/acre in 200 litres. Spray at seedling stage when thrips count exceeds 10/leaf. Seed treatment is preferred.",
        "prevention": [
            "Seed treatment with Imidacloprid (5 g/kg seed) or Thiamethoxam (4 g/kg seed)",
            "Avoid sowing near onion or chilli fields which are thrips reservoirs",
            "Maintain weed-free borders",
            "Conserve natural enemies like minute pirate bugs",
        ],
    },
    "Cotton___Wilt": {
        "disease_name": "Cotton Wilt",
        "crop": "Cotton",
        "symptoms": [
            "Sudden wilting of plants despite adequate soil moisture",
            "Yellowing of leaves starting from lower canopy",
            "Dark brown discolouration of vascular tissue visible when stem is cut",
            "Roots show brownish-black discolouration",
        ],
        "cause": "Fungus Fusarium oxysporum f. sp. vasinfectum — soil-borne, enters through roots and blocks vascular tissue",
        "description": "Cotton wilt (Fusarium wilt) is a soil-borne disease that clogs the plant's water-conducting vessels. It is prevalent in black cotton soils of Central India. Plants wilt and die despite irrigated conditions. Heavy soils with poor drainage are most susceptible.",
        "severity": "High",
        "spread_risk": "Medium",
        "organic_treatment": [
            "Seed treatment with Trichoderma viride (10 g/kg seed)",
            "Soil application of Trichoderma harzianum (2.5 kg/acre) mixed with FYM",
            "Apply Pseudomonas fluorescens (10 g/litre) as root drench",
            "Incorporate mustard cake (100 kg/acre) as soil amendment",
        ],
        "chemical_treatment": [
            "Carbendazim 50% WP (Bavistin) — 1 g/litre root drench",
            "Thiophanate Methyl 70% WP (Topsin-M) — 1 g/litre root drench",
            "No effective foliar chemical once wilt symptoms are advanced",
        ],
        "dosage": "Carbendazim: Drench 200 ml solution per plant at base. Apply at first wilting symptom. Preventive treatment at 30 and 60 days after sowing.",
        "prevention": [
            "Grow wilt-resistant varieties (Suraj, NH 615, MCU 5)",
            "Long crop rotation (3+ years) with cereals or pulses",
            "Avoid waterlogging — ensure proper drainage",
            "Deep summer ploughing to reduce soil inoculum",
            "Avoid root injury during intercultural operations",
        ],
    },

    # ═══════════════════════════════════════════════════════════════════
    #   ADDITIONAL WHEAT DISEASES & PESTS
    # ═══════════════════════════════════════════════════════════════════
    "Wheat___Flag_Smut": {
        "disease_name": "Wheat Flag Smut",
        "crop": "Wheat",
        "symptoms": [
            "Long grey-black streaks (sori) parallel to leaf veins",
            "Streaks rupture to release dark powdery spores",
            "Infected leaves twist, shred, and roll",
            "Severely infected plants may not produce ears",
        ],
        "cause": "Fungus Urocystis agropyri — soil-borne, infects at seedling stage",
        "description": "Flag smut produces long dark smut streaks on leaves. While not as devastating as other smuts, it can cause 15–25% yield loss in endemic areas. It is more common in irrigated wheat regions of northern India.",
        "severity": "Medium",
        "spread_risk": "Low",
        "organic_treatment": [
            "Seed treatment with Trichoderma viride (4 g/kg seed)",
            "Remove and destroy infected plants before spore dispersal",
            "Apply organic matter to improve soil health and microbial antagonism",
        ],
        "chemical_treatment": [
            "Carboxin 37.5% + Thiram 37.5% DS (Vitavax Power) — 2.5 g/kg seed treatment",
            "Carbendazim 50% WP (Bavistin) — 2 g/kg seed treatment",
        ],
        "dosage": "Vitavax Power: 2.5 g/kg seed. Mix thoroughly and dry in shade before sowing.",
        "prevention": [
            "Mandatory seed treatment before every sowing",
            "Use certified disease-free seed",
            "Avoid continuous wheat cropping — rotate with pulses or oilseeds",
        ],
    },
    "Wheat___Leaf_Smut": {
        "disease_name": "Wheat Leaf Smut",
        "crop": "Wheat",
        "symptoms": [
            "Small dark oval sori on leaf blades",
            "Sori covered by a thin silvery membrane that ruptures to release spores",
            "Leaves may show chlorotic spots around sori",
        ],
        "cause": "Fungus Entyloma tritici — mild, locally occurring smut disease",
        "description": "Wheat leaf smut is generally a minor disease but can be locally important. It reduces photosynthetic area slightly and is an indicator of poor seed health. Usually more cosmetic than yield-reducing.",
        "severity": "Low",
        "spread_risk": "Low",
        "organic_treatment": [
            "Seed treatment with Trichoderma viride (4 g/kg seed)",
            "Maintain balanced nutrition for plant vigor",
        ],
        "chemical_treatment": [
            "Carboxin 37.5% + Thiram 37.5% DS (Vitavax Power) — 2.5 g/kg seed",
            "Carbendazim 50% WP (Bavistin) — 2 g/kg seed treatment",
        ],
        "dosage": "Vitavax Power: 2.5 g/kg seed — seed treatment before sowing.",
        "prevention": [
            "Use certified disease-free seed",
            "Seed treatment as routine practice",
            "Crop rotation with non-cereals",
        ],
    },
    "Wheat___Black_Rust": {
        "disease_name": "Wheat Black Rust (Stem Rust)",
        "crop": "Wheat",
        "symptoms": [
            "Large dark reddish-brown to black pustules on stems, leaves, and leaf sheaths",
            "Pustules rupture the epidermis — rough to touch",
            "Stems weaken and may break (lodging)",
            "Shrivelled grains with poor filling",
        ],
        "cause": "Fungus Puccinia graminis tritici, spread by wind-borne uredospores over long distances",
        "description": "Black rust (stem rust) is the most destructive wheat rust but occurs less frequently in India than brown or yellow rust. When it does appear, yield losses can exceed 50%. It historically caused famines before resistant varieties were developed.",
        "severity": "High",
        "spread_risk": "High",
        "organic_treatment": [
            "Remove barberry (alternate host) from nearby areas",
            "Spray neem oil (5 ml/litre) at first pustule appearance",
            "Apply Trichoderma viride (4 g/litre) preventively",
        ],
        "chemical_treatment": [
            "Propiconazole 25% EC (Tilt) — 1 ml/litre",
            "Tebuconazole 25.9% EC (Folicur) — 1 ml/litre",
            "Mancozeb 75% WP (Dithane M-45) — 2.5 g/litre as preventive",
        ],
        "dosage": "Propiconazole: 200 ml/acre in 200 litres water. Spray at first pustule. May require second spray after 15 days.",
        "prevention": [
            "Grow resistant varieties (HD 3086, DBW 187)",
            "Avoid late sowing — late crops face higher rust pressure",
            "Monitor fields from February in North India",
            "Destroy volunteer wheat and barberry plants",
        ],
    },
    "Wheat___Yellow_Rust": {
        "disease_name": "Wheat Yellow Rust (Stripe Rust)",
        "crop": "Wheat",
        "symptoms": [
            "Yellow-orange pustules arranged in distinct stripes along leaf veins",
            "Pustules smaller than brown rust, in linear rows",
            "Severely infected leaves turn yellow and dry",
            "Poor ear development and shrivelled grains",
        ],
        "cause": "Fungus Puccinia striiformis tritici, favoured by cool temperatures (10–15°C) and humid conditions",
        "description": "Yellow rust is the most damaging wheat rust in the cooler hill and northern plains of India. It appears earlier than other rusts (December–January) and can cause 40–100% yield loss in susceptible varieties when conditions favour epidemics.",
        "severity": "High",
        "spread_risk": "High",
        "organic_treatment": [
            "Spray neem oil (5 ml/litre) at first Signs of stripe formation",
            "Apply Trichoderma viride (4 g/litre) as preventive",
            "Monitor fields weekly from December in North India",
        ],
        "chemical_treatment": [
            "Propiconazole 25% EC (Tilt) — 1 ml/litre",
            "Tebuconazole 25.9% EC (Folicur) — 1 ml/litre",
            "Trifloxystrobin 25% + Tebuconazole 50% WG (Nativo) — 0.4 g/litre",
        ],
        "dosage": "Propiconazole: 200 ml/acre in 200 litres. Spray immediately on detection. Repeat after 15 days if needed.",
        "prevention": [
            "Grow resistant varieties — check latest recommendations from IIWBR",
            "Timely sowing (November) — late crops face higher risk",
            "Avoid excess nitrogen which creates dense, humid canopy",
            "Community-level surveillance for early warning",
        ],
    },
    "Wheat___Leaf_Blight": {
        "disease_name": "Wheat Leaf Blight",
        "crop": "Wheat",
        "symptoms": [
            "Irregular brown necrotic patches on leaves",
            "Lesions may have yellow halo margins",
            "Severely infected leaves dry from tip downwards",
            "Reduced grain filling in late infections",
        ],
        "cause": "Bipolaris sorokiniana (spot blotch) and Alternaria triticina — favoured by warm humid weather",
        "description": "Wheat leaf blight complex (spot blotch + Alternaria blight) is a major constraint in the warmer wheat-growing regions of eastern India (Bihar, eastern UP, West Bengal). Yield losses of 15–25% are common in susceptible varieties.",
        "severity": "Medium",
        "spread_risk": "Medium",
        "organic_treatment": [
            "Spray Trichoderma viride (4 g/litre) at tillering and booting stages",
            "Apply neem oil (5 ml/litre) at 15-day intervals",
            "Remove heavily infected lower leaves",
        ],
        "chemical_treatment": [
            "Propiconazole 25% EC (Tilt) — 1 ml/litre",
            "Mancozeb 75% WP (Dithane M-45) — 2.5 g/litre",
            "Carbendazim 12% + Mancozeb 63% WP (SAAF) — 2 g/litre",
        ],
        "dosage": "Propiconazole: 200 ml/acre in 200 litres. Two sprays at 50 and 70 days after sowing.",
        "prevention": [
            "Grow resistant varieties (HD 2967, DBW 39)",
            "Timely sowing — avoid late planting",
            "Balanced NPK with adequate potassium",
            "Avoid excess irrigation during grain filling",
        ],
    },
    "Wheat___Scab": {
        "disease_name": "Wheat Head Scab (Fusarium Head Blight)",
        "crop": "Wheat",
        "symptoms": [
            "Premature bleaching of individual spikelets on the ear",
            "Pink or orange fungal growth at the base of infected spikelets",
            "Shrivelled, chalky-white or pinkish grains",
            "Blackening of the rachis in severe cases",
        ],
        "cause": "Fusarium graminearum — favoured by warm, wet weather during anthesis (flowering)",
        "description": "Wheat scab is a serious quality and yield concern. It not only reduces grain weight but also produces mycotoxins (deoxynivalenol/DON) that are harmful to humans and livestock. The disease is sporadic but devastating when it occurs.",
        "severity": "High",
        "spread_risk": "Medium",
        "organic_treatment": [
            "Remove crop residues — Fusarium survives on corn/wheat stubble",
            "Apply Trichoderma viride (4 g/litre) at heading stage",
            "Avoid overhead irrigation during flowering",
        ],
        "chemical_treatment": [
            "Tebuconazole 25.9% EC (Folicur) — 1 ml/litre at anthesis",
            "Propiconazole 25% EC (Tilt) — 1 ml/litre",
            "Carbendazim 50% WP (Bavistin) — 1 g/litre",
        ],
        "dosage": "Tebuconazole: 200 ml/acre in 200 litres. Spray at early anthesis (50% heads flowering). Timing is critical.",
        "prevention": [
            "Rotate with non-cereal crops — avoid wheat after maize",
            "Plough under crop residues to accelerate decomposition",
            "Avoid excess nitrogen which delays maturity into wet season",
            "Grow moderately resistant varieties where available",
        ],
    },
    "Wheat___Stem_Fly": {
        "disease_name": "Wheat Stem Fly",
        "crop": "Wheat",
        "symptoms": [
            "Central shoot dries up (dead heart) in young plants",
            "Small maggot visible inside the stem when split open",
            "Stem shows brownish internal damage from maggot feeding",
            "Reduced tillering and stunted growth",
        ],
        "cause": "Atherigona sp. (shoot fly) — maggot bores into stem and kills the growing point",
        "description": "Wheat stem fly causes dead hearts in young wheat plants by boring into the central stem. It is more common in late-sown wheat and in warmer regions of peninsular India. Yield loss of 10–20% in late-sown crops.",
        "severity": "Medium",
        "spread_risk": "Low",
        "organic_treatment": [
            "Apply neem seed kernel extract (NSKE 5%) at seedling stage",
            "Spray neem oil (5 ml/litre) at 15 days after sowing",
            "Pull out and destroy dead heart shoots",
        ],
        "chemical_treatment": [
            "Imidacloprid 17.8% SL (Confidor) — 0.3 ml/litre as spray",
            "Fipronil 5% SC (Regent) — 2 ml/litre",
            "Seed treatment with Imidacloprid (5 g/kg seed) is most effective",
        ],
        "dosage": "Seed treatment: Imidacloprid 5 g/kg seed. Foliar: Imidacloprid 60 ml/acre if stem fly incidence exceeds 10%.",
        "prevention": [
            "Timely sowing (November 1–15 in North India) — late sowing increases risk",
            "Seed treatment with Imidacloprid is the best preventive measure",
            "Avoid continuous wheat — rotate with mustard or pulses",
            "Maintain optimum seed rate for vigorous stand establishment",
        ],
    },
    "Wheat___Aphid": {
        "disease_name": "Wheat Aphid",
        "crop": "Wheat",
        "symptoms": [
            "Clusters of small green or brown aphids on leaves, stems, and ears",
            "Yellowing and curling of leaves",
            "Honeydew deposits leading to sooty mould",
            "Reduced grain filling and shrivelled grains",
        ],
        "cause": "Sitobion avenae and Rhopalosiphum padi — sap-sucking insects that multiply rapidly in February–March",
        "description": "Wheat aphid is a major pest across the Indo-Gangetic plains, appearing during heading and grain-filling stages. Large colonies on the ear can reduce grain weight by 15–30%. They also transmit Barley Yellow Dwarf Virus (BYDV).",
        "severity": "Medium",
        "spread_risk": "High",
        "organic_treatment": [
            "Spray neem oil (5 ml/litre) when colonies first appear",
            "Release ladybird beetles — effective natural predator",
            "Apply tobacco decoction (500 g tobacco in 10 litres water)",
        ],
        "chemical_treatment": [
            "Imidacloprid 17.8% SL (Confidor) — 0.3 ml/litre",
            "Thiamethoxam 25% WG (Actara) — 0.3 g/litre",
            "Dimethoate 30% EC (Rogor) — 1.7 ml/litre",
        ],
        "dosage": "Imidacloprid: 60 ml/acre in 200 litres. Spray when aphid count exceeds 10 per ear. One spray usually sufficient.",
        "prevention": [
            "Timely sowing — late-sown crops face more aphid pressure",
            "Avoid excess nitrogen — promotes lush growth attracting aphids",
            "Conserve natural enemies — ladybirds, lacewings, syrphid flies",
            "Monitor fields from February onwards",
        ],
    },
    "Wheat___Mite": {
        "disease_name": "Wheat Mite",
        "crop": "Wheat",
        "symptoms": [
            "Silvery white or yellow stippling on upper leaf surface",
            "Leaf margins may curl inward",
            "Fine webbing visible on leaf undersides in heavy infestations",
            "Leaves dry out from margins in severe cases",
        ],
        "cause": "Petrobia latens (brown wheat mite) — tiny mites that pierce leaf cells and suck sap",
        "description": "Wheat mites are occasional pests in dry, warm conditions. Brown wheat mite (Petrobia latens) can cause silvery stippling and leaf drying. They are usually controlled naturally by rainfall and predatory mites. Yield loss is typically 5–15%.",
        "severity": "Low",
        "spread_risk": "Low",
        "organic_treatment": [
            "Spray wettable sulphur (3 g/litre) — effective acaricide",
            "Apply neem oil (5 ml/litre) at 10-day intervals",
            "Maintain adequate irrigation — drought stress worsens mite damage",
        ],
        "chemical_treatment": [
            "Dicofol 18.5% EC (Kelthane) — 2.5 ml/litre",
            "Wettable Sulphur 80% WP (Sulfex) — 3 g/litre",
            "Propargite 57% EC (Omite) — 1 ml/litre",
        ],
        "dosage": "Wettable Sulphur: 600 g/acre in 200 litres. Spray when mite population is noticeable. One or two sprays sufficient.",
        "prevention": [
            "Maintain adequate irrigation — avoid drought stress",
            "Avoid excess use of broad-spectrum insecticides that kill predatory mites",
            "Monitor fields during dry spells in February–March",
        ],
    },

    # ═══════════════════════════════════════════════════════════════════
    #   ADDITIONAL RICE DISEASES
    # ═══════════════════════════════════════════════════════════════════
    "Rice___Tungro": {
        "disease_name": "Rice Tungro",
        "crop": "Rice",
        "symptoms": [
            "Yellowing to orange discolouration of leaves starting from tip",
            "Stunted plant growth with reduced tillering",
            "Leaves become mottled with irregular yellow-green patches",
            "Delayed or no heading in severely affected plants",
        ],
        "cause": "Rice Tungro Virus complex (RTSV + RTBV), transmitted by green leafhopper (Nephotettix virescens)",
        "description": "Rice tungro is one of the most devastating viral diseases of rice in South and Southeast Asia. In India, it is most severe in Southern states (Andhra Pradesh, Tamil Nadu, Kerala). Yield losses can reach 40–100% in epidemic years.",
        "severity": "High",
        "spread_risk": "High",
        "organic_treatment": [
            "Install yellow sticky traps and light traps to monitor leafhopper vectors",
            "Spray neem oil (5 ml/litre) to repel leafhoppers",
            "Release egg parasitoid Anagrus flaveolus against leafhoppers",
            "Uproot and destroy infected plants immediately to prevent virus spread",
        ],
        "chemical_treatment": [
            "Imidacloprid 17.8% SL (Confidor) — 0.3 ml/litre for leafhopper control",
            "Thiamethoxam 25% WG (Actara) — 0.3 g/litre",
            "Carbofuran 3% CG (Furadan) — 12.5 kg/acre (soil application at transplanting)",
            "No chemical cure for virus once plant is infected — manage vector only",
        ],
        "dosage": "Imidacloprid: 60 ml/acre in 200 litres. Apply at transplanting and repeat at 15-day intervals during leafhopper peak.",
        "prevention": [
            "Grow tungro-resistant varieties (IR64, Vikramarya, Surekha)",
            "Synchronised planting in the community to reduce staggered crops",
            "Destroy crop ratoons and volunteer plants after harvest",
            "Maintain proper spacing and avoid dense planting",
            "Nursery treatment with Imidacloprid seed soak",
        ],
    },

    # ═══════════════════════════════════════════════════════════════════
    #   ADDITIONAL MAIZE DISEASES & PESTS
    # ═══════════════════════════════════════════════════════════════════
    "Maize___Gray_Leaf_Spot": {
        "disease_name": "Maize Gray Leaf Spot",
        "crop": "Maize",
        "symptoms": [
            "Rectangular grey-tan lesions running parallel to leaf veins",
            "Lesions have sharply defined edges bounded by veins",
            "Lesions coalesce in severe cases, blighting entire leaves",
            "Lower leaves affected first, progressing upward",
        ],
        "cause": "Fungus Cercospora zeae-maydis — favoured by humid conditions and minimum tillage",
        "description": "Gray leaf spot is an increasing concern in Indian maize, especially in areas with conservation tillage where crop residues remain on the surface. Yield losses of 20–40% can occur when lesions develop before tasseling.",
        "severity": "Medium",
        "spread_risk": "Medium",
        "organic_treatment": [
            "Remove and destroy crop residues after harvest",
            "Apply Trichoderma viride (4 g/litre) as preventive foliar spray",
            "Spray Pseudomonas fluorescens (10 g/litre) at early lesion stage",
        ],
        "chemical_treatment": [
            "Azoxystrobin 23% SC (Amistar) — 1 ml/litre",
            "Propiconazole 25% EC (Tilt) — 1 ml/litre",
            "Mancozeb 75% WP (Dithane M-45) — 2.5 g/litre",
        ],
        "dosage": "Azoxystrobin: 200 ml/acre in 200 litres. Spray at V8–VT stage when lesions first appear.",
        "prevention": [
            "Rotate with non-cereal crops for at least one season",
            "Plough under crop residues to reduce inoculum",
            "Grow tolerant hybrids",
            "Maintain balanced nutrition with adequate potassium",
        ],
    },
    "Maize___Armyworm": {
        "disease_name": "Maize Armyworm",
        "crop": "Maize",
        "symptoms": [
            "Irregular holes and ragged edges on leaves",
            "Whorl leaves show extensive feeding damage",
            "Frass (excreta) visible in leaf whorls",
            "Larvae found hidden inside the leaf whorl",
        ],
        "cause": "Mythimna separata (common armyworm) — gregarious caterpillars that migrate and feed in armies",
        "description": "Armyworm outbreaks are sporadic but devastating in Indian maize. Larvae feed gregariously and can strip entire fields overnight. They are most active during monsoon season and migrate in swarms across fields.",
        "severity": "High",
        "spread_risk": "High",
        "organic_treatment": [
            "Install light traps (1/acre) to monitor moth activity",
            "Spray NSKE 5% or neem oil (5 ml/litre)",
            "Release Trichogramma chilonis (1 lakh/acre) for egg parasitisation",
            "Hand-collect larvae in early morning from whorls",
        ],
        "chemical_treatment": [
            "Emamectin Benzoate 5% SG (Proclaim) — 4 g/10 litres",
            "Chlorantraniliprole 18.5% SC (Coragen) — 3 ml/10 litres",
            "Lambda Cyhalothrin 5% EC (Karate) — 1 ml/litre",
        ],
        "dosage": "Emamectin Benzoate: 80 g/acre in 200 litres. Spray into leaf whorls in evening. One spray usually sufficient.",
        "prevention": [
            "Plough fields between seasons to expose pupae",
            "Light traps for early warning of moth migration",
            "Timely sowing — avoid coincidence with monsoon peak",
            "Maintain weed-free borders",
        ],
    },
    "Maize___Fall_Armyworm": {
        "disease_name": "Maize Fall Armyworm",
        "crop": "Maize",
        "symptoms": [
            "Windowing of leaves — transparent patches where epidermis is eaten",
            "Extensive whorl damage with copious frass",
            "Large ragged holes in leaves",
            "Larvae bore into ears and feed on developing kernels",
        ],
        "cause": "Spodoptera frugiperda — invasive pest from Americas, entered India in 2018",
        "description": "Fall armyworm (FAW) is a devastating invasive pest that arrived in India in 2018 and has since spread across all maize-growing states. FAW is harder to control than native armyworms due to its rapid reproduction and tolerance to many insecticides. Yield losses of 30–60% are common without management.",
        "severity": "High",
        "spread_risk": "High",
        "organic_treatment": [
            "Apply NSKE 5% or neem oil (5 ml/litre) into leaf whorls",
            "Release Telenomus remus (50,000/acre) — specific egg parasitoid for FAW",
            "Spray Metarhizium rileyi (5 g/litre) — entomopathogenic fungus",
            "Install pheromone traps (5/acre) for monitoring and mass trapping",
            "Apply sand + lime mixture (9:1) into whorls",
        ],
        "chemical_treatment": [
            "Spinetoram 11.7% SC (Delegate) — 4 ml/10 litres",
            "Chlorantraniliprole 18.5% SC (Coragen) — 3 ml/10 litres",
            "Emamectin Benzoate 5% SG (Proclaim) — 4 g/10 litres",
            "Thiamethoxam 12.6% + Lambda Cyhalothrin 9.5% ZC (Alika) — 0.5 ml/litre",
        ],
        "dosage": "Spinetoram: 80 ml/acre in 200 litres. Spray into whorls targeting early-instar larvae. Rotate mode of action every spray.",
        "prevention": [
            "Intercrop with pulses or cowpea to reduce FAW incidence",
            "Use pheromone traps for early warning",
            "Plough and destroy crop residues promptly after harvest",
            "Follow ICAR recommended IPM package for FAW",
            "Plant trap crop borders (Napier grass) around maize fields",
        ],
    },
    "Maize___Ear_Rot": {
        "disease_name": "Maize Ear Rot",
        "crop": "Maize",
        "symptoms": [
            "White, pink, or blue-green mould on ear surface",
            "Kernels show discolouration and rotting",
            "Soft, mushy kernels with foul or musty smell",
            "Mycotoxin contamination makes grain unsuitable for consumption",
        ],
        "cause": "Fusarium verticillioides, Aspergillus flavus, or Stenocarpella maydis — infection through silk channel or insect damage",
        "description": "Maize ear rot is a complex of fungal diseases causing kernel discolouration, reduced quality, and mycotoxin contamination (fumonisins, aflatoxins). It is particularly serious in stored grain. Ear rot can cause 10–30% yield loss and makes grain dangerous for food and feed.",
        "severity": "High",
        "spread_risk": "Medium",
        "organic_treatment": [
            "Spray Trichoderma viride (4 g/litre) at silk emergence",
            "Ensure good husk coverage over ear tip — tight husks reduce infection",
            "Harvest at physiological maturity — avoid delayed harvest",
            "Dry grain to below 15% moisture immediately after harvest",
        ],
        "chemical_treatment": [
            "Carbendazim 50% WP (Bavistin) — 1 g/litre spray at silk stage",
            "Mancozeb 75% WP (Dithane M-45) — 2.5 g/litre at silk stage",
        ],
        "dosage": "Carbendazim: 200 g/acre in 200 litres. Spray at 50% silking. Efficacy is limited once infection is inside the ear.",
        "prevention": [
            "Harvest promptly — don't leave mature ears in field during rains",
            "Dry grain rapidly to <14% moisture for safe storage",
            "Control ear borers and FAW — insect damage is primary entry point",
            "Grow hybrids with good husk coverage and ear rot tolerance",
            "Store grain in clean, dry, well-ventilated structures",
        ],
    },
    "Maize___Stem_Borer": {
        "disease_name": "Maize Stem Borer",
        "crop": "Maize",
        "symptoms": [
            "Dead heart in young plants — central leaf whorl wilts and dries",
            "Pin holes on young leaves in a row (shot-hole damage from boring)",
            "Stem shows tunnelling when split open",
            "Frass pushed out from bore holes on stem",
        ],
        "cause": "Chilo partellus (spotted stem borer) — larvae bore into stems and feed on internal tissue",
        "description": "Maize stem borer is the most serious insect pest of maize in India. Larvae kill the growing point causing dead hearts, then tunnel through stems reducing plant strength and nutrient transport. Yield losses of 25–40% in kharif maize.",
        "severity": "High",
        "spread_risk": "Medium",
        "organic_treatment": [
            "Release Trichogramma chilonis (1 lakh eggs/acre) at 15-day intervals",
            "Apply Bacillus thuringiensis (Bt) spray (2 g/litre) into whorls",
            "Spray NSKE 5% at 10-day intervals from germination",
            "Install light traps for moth monitoring",
        ],
        "chemical_treatment": [
            "Carbofuran 3% CG (Furadan) — 4–5 granules per whorl at 15–20 DAS",
            "Fipronil 0.3% GR — 6–8 kg/acre into leaf whorls",
            "Chlorantraniliprole 0.4% GR (Ferterra) — 4 kg/acre",
            "Emamectin Benzoate 5% SG (Proclaim) — 4 g/10 litres spray",
        ],
        "dosage": "Carbofuran granules: 4–5 granules per whorl at 15 and 30 DAS. Apply in morning when leaves are dewy for granules to settle.",
        "prevention": [
            "Timely sowing — early sowing escapes peak borer activity",
            "Remove and destroy crop stubbles after harvest",
            "Intercrop with cowpea or beans to reduce borer pressure",
            "Use resistant/tolerant hybrids where available",
        ],
    },

    # ═══════════════════════════════════════════════════════════════════
    #   ADDITIONAL SUGARCANE DISEASES
    # ═══════════════════════════════════════════════════════════════════
    "Sugarcane___Mosaic": {
        "disease_name": "Sugarcane Mosaic",
        "crop": "Sugarcane",
        "symptoms": [
            "Light and dark green mosaic (mottling) pattern on young leaves",
            "Irregular chlorotic streaks parallel to leaf veins",
            "Stunted stalk growth in severe infections",
            "Reduced sucrose content in affected canes",
        ],
        "cause": "Sugarcane Mosaic Virus (ScMV), transmitted by aphids (Rhopalosiphum maidis)",
        "description": "Sugarcane mosaic is a widespread viral disease in India affecting both sugarcane and sorghum. It reduces photosynthetic efficiency and sugarcane recovery. Yield losses of 10–25% in moderately affected ratoon crops. The virus persists through infected setts.",
        "severity": "Medium",
        "spread_risk": "Medium",
        "organic_treatment": [
            "Remove and destroy infected plants (roguing) to reduce virus source",
            "Control aphid vectors with neem oil (5 ml/litre) spray",
            "Hot water treatment of setts at 52°C for 30 minutes",
            "Use meristem-cultured (tissue culture) disease-free planting material",
        ],
        "chemical_treatment": [
            "Imidacloprid 17.8% SL (Confidor) — 0.3 ml/litre for aphid control",
            "Thiamethoxam 25% WG (Actara) — 0.3 g/litre for aphid management",
            "No direct chemical cure for the virus — manage vector only",
        ],
        "dosage": "Imidacloprid: 60 ml/acre in 200 litres. Spray when aphid colonies appear on young cane.",
        "prevention": [
            "Use certified virus-free seed cane",
            "Hot water treatment of setts before planting",
            "Grow mosaic-resistant varieties (Co 0238, CoLk 94184)",
            "Rogue out symptomatic plants within 3 months of planting",
            "Avoid using setts from mosaic-affected fields for propagation",
        ],
    },
    "Sugarcane___Red_Rust": {
        "disease_name": "Sugarcane Red Rust",
        "crop": "Sugarcane",
        "symptoms": [
            "Reddish-brown elongated pustules on leaf surfaces",
            "Pustules rupture to release rusty-brown spores",
            "Yellowing around pustules",
            "Premature drying of affected leaves",
        ],
        "cause": "Fungus Puccinia melanocephala — spread by wind-borne spores, favoured by warm humid weather",
        "description": "Red rust of sugarcane can reduce cane yield by 10–20% and sucrose content by weakening the plant. It is more common on susceptible varieties and during rainy season when humidity is high. Usually more severe on ratoon crops.",
        "severity": "Medium",
        "spread_risk": "Medium",
        "organic_treatment": [
            "Remove severely infected leaves",
            "Spray neem oil (5 ml/litre) at first symptom",
            "Apply Trichoderma viride (4 g/litre) foliar spray",
        ],
        "chemical_treatment": [
            "Propiconazole 25% EC (Tilt) — 1 ml/litre",
            "Mancozeb 75% WP (Dithane M-45) — 2.5 g/litre",
            "Triadimefon 25% WP (Bayleton) — 1 g/litre",
        ],
        "dosage": "Propiconazole: 200 ml/acre in 200 litres. Spray at first symptoms and repeat after 15 days if needed.",
        "prevention": [
            "Grow rust-resistant varieties",
            "Avoid ratooning susceptible varieties beyond 2 cycles",
            "Maintain balanced fertilisation",
        ],
    },
    "Sugarcane___Yellow_Rust": {
        "disease_name": "Sugarcane Yellow Rust",
        "crop": "Sugarcane",
        "symptoms": [
            "Yellow to orange pustules on underside of leaves",
            "Pustules appear in clusters on lower leaves first",
            "Leaf yellowing and premature senescence",
        ],
        "cause": "Fungus Puccinia kuehnii — spread by wind-borne spores, favoured by cool wet conditions",
        "description": "Yellow rust (orange rust) of sugarcane is a relatively newer concern in India. It reduces photosynthetic area and can cause 10–15% yield loss in susceptible varieties. The disease is managed similarly to red rust.",
        "severity": "Medium",
        "spread_risk": "Medium",
        "organic_treatment": [
            "Remove and destroy heavily infected leaves",
            "Apply Trichoderma viride (4 g/litre) preventively",
            "Spray neem oil (5 ml/litre)",
        ],
        "chemical_treatment": [
            "Propiconazole 25% EC (Tilt) — 1 ml/litre",
            "Mancozeb 75% WP (Dithane M-45) — 2.5 g/litre",
        ],
        "dosage": "Propiconazole: 200 ml/acre in 200 litres. Spray at first pustule appearance.",
        "prevention": [
            "Grow resistant varieties (Co 0238)",
            "Maintain proper drainage",
            "Avoid excess nitrogen",
        ],
    },
}


def get_disease_info(class_key: str) -> dict | None:
    """Look up disease by class key (e.g. 'Tomato___Late_Blight')."""
    return DISEASE_DATABASE.get(class_key)


def get_all_diseases() -> list[dict]:
    """Return list of all disease documents."""
    return [
        {**v, "class_key": k}
        for k, v in DISEASE_DATABASE.items()
        if v["disease_name"] != "Healthy"
    ]


def get_diseases_by_crop(crop: str) -> list[dict]:
    """Return diseases for a specific crop."""
    return [
        {**v, "class_key": k}
        for k, v in DISEASE_DATABASE.items()
        if v["crop"].lower() == crop.lower() and v["disease_name"] != "Healthy"
    ]


# Class index mapping — matches training label encoding order
# Update this after training your model
CLASS_INDEX_MAP = {i: key for i, key in enumerate(DISEASE_DATABASE.keys())}
INDEX_CLASS_MAP = {v: k for k, v in CLASS_INDEX_MAP.items()}
